telegram:
  token: "7621336869:AAE-d3lH-Y7cH_ljKGkDyhkPWwpxDfonRXQ"
  webhook_path: "/webhook/7621336869:AAE-d3lH-Y7cH_ljKGkDyhkPWwpxDfonRXQ"

yagpt:
  api_key: "y0__xD8_K6MCBjB3RMg9sPt8RIwyYivjAhazOSX7kyjRB8mzebu7l9FJAVbDQ"
  login: "hackaton-team1@yandex.ru"
  password: "MIPT2025dev"
  folder_id: "b1glp0iqac5h7ihhmh7b"

knowledge_base:
  db_url: "postgresql://user:password@localhost:5432/knowledge_db"
  top_k: 5

logging:
  level: "INFO"
  format: "%(asctime)s %(levelname)s %(name)s: %(message)s"
